[package]

name = "i2cdev"
build = "build.rs"
version = "0.3.1"
authors = ["Paul Osborne <osbpau@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-embedded/rust-i2cdev"
homepage = "https://github.com/rust-embedded/rust-i2cdev"
documentation = "http://rust-embedded.github.io/rust-i2cdev"
description = """
Provides API for safe access to Linux i2c device interface.

https://www.kernel.org/doc/Documentation/i2c/dev-interface
"""

[dependencies]
libc = ">= 0.2.7"
bitflags = ">= 0.5.0"
byteorder = ">= 0.4.2"
nix = ">= 0.9.0"

[dev-dependencies]
docopt = ">= 0.6.78"
skeptic = ">= 0.5"

[build-dependencies]
skeptic = ">= 0.5"
